export const ADD_PUSH_INFO = 'ADD_PUSH_INFO';
export const CHANGE_PUSH_INFO = 'CHANGE_PUSH_INFO';
export const DELETE_SINGLE_PUSH_INFO = 'DELETE_SINGLE_PUSH_INFO';
export const DELETE_LIST_PUSH_INFO = 'DELETE_LIST_PUSH_INFO';
export const DELETE_ALL_PUSH_INFO = 'DELETE_ALL_PUSH_INFO';
export const ADD_PUSH_ANNOUNCEMENT_INFO = 'ADD_PUSH_ANNOUNCEMENT_INFO';
export const CHANGE_PUSH_ANNOUNCEMENT_READ = 'CHANGE_PUSH_ANNOUNCEMENT_READ';